// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Article struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Ean         string      `json:"EAN"`
	Description string      `json:"description"`
	Category    []*Category `json:"category"`
	Images      []*Image    `json:"images"`
}

type CategoriesArticle struct {
	Name     string               `json:"name"`
	Children []*CategoriesArticle `json:"children"`
}

type Category struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    []*Category `json:"Category"`
}

type Image struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

type NewArticle struct {
	Name        string               `json:"name"`
	Ean         string               `json:"EAN"`
	ImgURI      *string              `json:"img_uri"`
	Description string               `json:"Description"`
	Categories  []*CategoriesArticle `json:"categories"`
	Images      []*NewImage          `json:"images"`
}

type NewCategory struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Category    []*NewCategory `json:"Category"`
}

type NewImage struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	URL         string          `json:"url"`
	File        *graphql.Upload `json:"file"`
}

type NewTransaction struct {
	Source   string `json:"source"`
	Receiver string `json:"receiver"`
	PDF      string `json:"pdf"`
	Date     string `json:"date"`
}

type Transaction struct {
	ID   string `json:"id"`
	Date string `json:"date"`
	PDF  string `json:"pdf"`
}
