// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Article struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Ean         string    `json:"EAN"`
	Description string    `json:"description"`
	Category    *Category `json:"category"`
	Images      []*Image  `json:"images"`
}

type Category struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    []*Category `json:"Category"`
}

type Image struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

type NewArticle struct {
	Name     string       `json:"name"`
	Ean      string       `json:"EAN"`
	ImgURI   *string      `json:"img_uri"`
	Category *NewCategory `json:"category"`
	Images   []*NewImage  `json:"images"`
}

type NewCategory struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Category    []*NewCategory `json:"Category"`
}

type NewImage struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	URL         string          `json:"url"`
	File        *graphql.Upload `json:"file"`
}

type NewTransaction struct {
	Name string          `json:"name"`
	PDF  *graphql.Upload `json:"pdf"`
	Date string          `json:"date"`
}

type NewUser struct {
	FullName    string  `json:"fullName"`
	Email       string  `json:"email"`
	ImgURI      *string `json:"img_uri"`
	DateCreated *string `json:"DateCreated"`
}

type ProfileImage struct {
	UserID *string         `json:"userId"`
	File   *graphql.Upload `json:"file"`
}

type Transaction struct {
	ID   string `json:"id"`
	Date string `json:"date"`
	PDF  string `json:"pdf"`
	User *User  `json:"user"`
}

type User struct {
	ID       string `json:"id"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	ImgURI   string `json:"img_uri"`
}
