// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ManuelLecaro/erpcore/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// IArticleRepository is an autogenerated mock type for the IArticleRepository type
type IArticleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, article
func (_m *IArticleRepository) Create(ctx context.Context, article domain.Article) (*domain.Article, error) {
	ret := _m.Called(ctx, article)

	var r0 *domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, domain.Article) *domain.Article); ok {
		r0 = rf(ctx, article)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Article) error); ok {
		r1 = rf(ctx, article)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IArticleRepository) GetByID(ctx context.Context, id string) (*domain.Article, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Article); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, fields
func (_m *IArticleRepository) Search(ctx context.Context, fields ...string) ([]*domain.Article, error) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, ...string) []*domain.Article); ok {
		r0 = rf(ctx, fields...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, fields...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIArticleRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIArticleRepository creates a new instance of IArticleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIArticleRepository(t mockConstructorTestingTNewIArticleRepository) *IArticleRepository {
	mock := &IArticleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
