// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ManuelLecaro/erpcore/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// ITransactionRepository is an autogenerated mock type for the ITransactionRepository type
type ITransactionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, transaction
func (_m *ITransactionRepository) Create(ctx context.Context, transaction domain.Transaction) (*domain.Transaction, error) {
	ret := _m.Called(ctx, transaction)

	var r0 *domain.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, domain.Transaction) *domain.Transaction); ok {
		r0 = rf(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewITransactionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewITransactionRepository creates a new instance of ITransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITransactionRepository(t mockConstructorTestingTNewITransactionRepository) *ITransactionRepository {
	mock := &ITransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
